import type { Writable } from 'node:stream'

const TEMPLATE = `# discord-mcp-plus configuration
# Generated by: npx discord-mcp-plus init

# Required
DISCORD_TOKEN=your-bot-token-here

# Optional — restricts all guild-scoped tools to this guild
# DISCORD_GUILD_ID=

# Safety — set to true to hide write/destructive tools from the AI
# DISCORD_MCP_READONLY=false

# Safety — comma-separated tool names to allow (all others hidden)
# DISCORD_MCP_TOOLS=

# Safety — comma-separated tool names to deny
# DISCORD_MCP_TOOLS_DENY=

# Safety — comma-separated channel IDs where write operations are permitted
# DISCORD_MCP_CHANNELS=

# Safety — intercept write/destructive calls and return a simulated response
# DISCORD_MCP_DRY_RUN=false

# Safety — require this secret token as confirmToken arg on all destructive tool calls
# DISCORD_MCP_CONFIRM_TOKEN=

# Audit — 'stderr' (default), 'off', or a file path
# DISCORD_MCP_AUDIT_LOG=stderr
`

export function printEnvTemplate(out: Writable = process.stdout as unknown as Writable): void {
  out.write(TEMPLATE)
}
